// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { config } from 'dotenv';
config()
const SUPABASE_URL = import.meta.env.VITE_PUBLIC_SUPABASE_URL || "https://lnbgdxadodrpwkftjzvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_PUBLIC_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuYmdkeGFkb2RycHdrZnRqenZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0ODY5NDgsImV4cCI6MjA2NjA2Mjk0OH0.rV4iJOslCj-8lz4SY7Rbmmc3GBFmQXkqO4NS1gMSf9M";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);